repos:
    -   repo: https://github.com/karolzak/pre-commit-nb
        rev: v0.1.0
        hooks:
            -   id: base64-to-image-files
                args: [--add_changes_to_staging, --auto_commit_changes]